title: "Álvaro González - Full Stack Developer & Maker"
description: "Portafolio de desarrollador Full-Stack chileno especializado en hardware libre, automatización y desarrollo creativo. Proyectos en Python, JavaScript, Lua y hardware embebido."

url: "https://4rgs.github.io"
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

# Theme - Usando remote_theme para GitHub Pages
remote_theme: pages-themes/hacker@v0.2.0

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme

# SEO settings
author: "Álvaro González"
github_username: "4rgs"

# Social links
social:
  name: "Álvaro González"
  links:
    - "https://github.com/4rgs"
    - "mailto:alvaro.gonzalez.dev@gmail.com"

# Site settings
show_excerpts: true
show_downloads: false

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name/

# Default layouts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "default"
  - scope:
      path: "projects"
      type: "pages"
    values:
      layout: "default"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - SETUP_GUIDE.md

# Include in processing
include:
  - _pages